name: dev
color: "#CE4F3B"
variables:
  - name: APIaddress
    value: http://localhost:3000/api
  - secret: true
    name: JWT
  - name: artist_babymetal
    value: 69e71abda1e1b090a92e1d62
  - name: artist_MRSGREENAPPLE
    value: 69f042fac4fdca569efc8a5e
  - name: artist_yorushika
    value: 69f03d3bc4fdca569efc8a43
  - name: artist_BANDMAID
    value: ""
  - name: artist_riho-sayashi
    value: ""
  - name: artist_ryokushaka
    value: ""
  - name: artist_nogizaka46
    value: ""
  - name: artist_ado
    value: ""
  - name: artist_hanabie
    value: ""
  - name: artist_haku
    value: ""
  - name: cat_merch-oficial
    value: ""
  - name: cat_accessories
    value: ""
  - name: cat_cd-dvd-bluray
    value: ""
  - name: cat_tour-merch
    value: ""
  - name: cat_apparel
    value: ""
  - name: cat_tote-bags
    value: ""
  - name: cat_keychains
    value: ""
  - name: cat_acrylic-stands
    value: ""
  - name: cat_stationery
    value: ""
