name: dev
color: "#CE4F3B"
variables:
  - name: APIaddress
    value: http://localhost:3000/api
  - secret: true
    name: JWT
  - name: artist_babymetal
    value: 69e71abda1e1b090a92e1d62
  - name: artist_MRSGREENAPPLE
    value: 69f042fac4fdca569efc8a5e
  - name: artist_yorushika
    value: 69f03d3bc4fdca569efc8a43
  - name: artist_BANDMAID
    value: 69f27a6b15e722f62b5ecb91
  - name: artist_riho-sayashi
    value: 69f27a7715e722f62b5ecb94
  - name: artist_ryokushaka
    value: 69f27a7f15e722f62b5ecb97
  - name: artist_nogizaka46
    value: 69f27a8515e722f62b5ecb9a
  - name: artist_ado
    value: 69f27a8d15e722f62b5ecb9d
  - name: artist_hanabie
    value: 69f27a9315e722f62b5ecba0
  - name: artist_haku
    value: 69f27a9715e722f62b5ecba3
  - name: cat_accessories
    value: 69f26889d075c554c978fdb2
  - name: cat_tourmerch
    value: 69f2679ed075c554c978fd9e
  - name: cat_apparel
    value: 69f267a4d075c554c978fda1
  - name: cat_keychains
    value: 69f26b33d075c554c978fdc1
  - name: cat_acrylicstands
    value: 69f26b38d075c554c978fdc4
  - name: cat_stationery
    value: 69f26b3dd075c554c978fdc7
  - name: cat_photobooks
    value: 69f26b49d075c554c978fdca
  - name: cat_merchoficial
    value: 69f2651cd075c554c978fd7e
  - name: cat_cddvdbluray
    value: 69f265add075c554c978fd8e
  - name: cat_totebags
    value: 69f26b26d075c554c978fdbe
